# @format
name: DeepSeek Code Review
on:
  issue_comment:
    types:
      - created
permissions:
  pull-requests: write
  issues: write
jobs:
  deepseek-review:
    if: >-
      github.event.issue.pull_request &&
      contains(github.event.comment.body, '@deepseek') &&
      contains(fromJSON('["OWNER","MEMBER","COLLABORATOR"]'), github.event.comment.author_association)
    timeout-minutes: 30
    runs-on: ubuntu-latest
    name: DeepSeek Code Review
    steps:
      - name: Acknowledge comment
        uses: tomgrv/actions/confirm-pr-comment@v2
        with:
          reaction: eyes

      - name: DeepSeek Code Review
        uses: hustcer/deepseek-review@v1
        with:
          chat-token: ${{ secrets.DEEPSEEK_CHAT_TOKEN }}
          watch-mention: '@deepseek'
          github-token: ${{ github.token }}
