# @format

name: Validate PR Format

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

permissions:
  contents: read
  pull-requests: write

jobs:
  validate-pr-title:
    name: Validate PR Title
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: npm ci && npm install -D $(jq -r '.commitlint.extends[]' 'package.json' | sed 's/^gitmoji$/commitlint-config-gitmoji/' | tr '\n' ' ')

      - name: Commitlint PR title
        run: echo "${{ github.event.pull_request.title }}" | npx commitlint
