---
name: "Test PR Workflow"

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches: [main]

jobs:
  test-pr-triggers:
    name: "Test PR Workflow Triggers"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Test PR trigger mechanism
        run: |
          echo "PR workflow triggered successfully"
          echo "Event: ${{ github.event_name }}"
          echo "PR Number: ${{ github.event.number }}"
          echo "Base Branch: ${{ github.base_ref }}"
          echo "Head Branch: ${{ github.head_ref }}"

      - name: Validate workflow files exist
        run: |
          if [ ! -f .github/workflows/validate.yml ]; then
            echo "ERROR: validate.yml workflow not found"
            exit 1
          fi
          if [ ! -f .github/workflows/release.yaml ]; then
            echo "ERROR: release.yaml workflow not found"
            exit 1
          fi
          echo "All required workflow files found"

      - name: Test devcontainer validation
        run: |
          # Test that devcontainer features are valid
          find src -name "devcontainer-feature.json" | while read file; do
            echo "Validating $file"
            if ! jq empty "$file" 2>/dev/null; then
              echo "ERROR: Invalid JSON in $file"
              exit 1
            fi
            echo "✓ $file is valid JSON"
          done

  test-status-checks:
    name: "Test Required Status Checks"
    runs-on: ubuntu-latest
    needs: test-pr-triggers
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Verify validate workflow can run
        run: |
          echo "Testing that validate workflow would run..."
          # Check if the validate workflow has proper structure
          if grep -q "devcontainers/action@v1" .github/workflows/validate.yml; then
            echo "✓ Validate workflow uses devcontainers action"
          else
            echo "ERROR: Validate workflow missing devcontainers action"
            exit 1
          fi

      - name: Test feature validation
        uses: devcontainers/action@v1
        with:
          validate-only: "true"
          base-path-to-features: "./src"

      - name: Verify all features have required files
        run: |
          for feature_dir in src/*/; do
            feature_name=$(basename "$feature_dir")
            echo "Checking feature: $feature_name"

            if [ ! -f "$feature_dir/devcontainer-feature.json" ]; then
              echo "ERROR: Missing devcontainer-feature.json in $feature_name"
              exit 1
            fi

            if [ ! -f "$feature_dir/install.sh" ]; then
              echo "ERROR: Missing install.sh in $feature_name"
              exit 1
            fi

            echo "✓ $feature_name has required files"
          done

  test-merge-requirements:
    name: "Test Merge Requirements"
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    needs: [test-pr-triggers, test-status-checks]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Simulate merge requirement check
        run: |
          echo "Testing merge requirements..."
          echo "All previous jobs must pass for this to run"
          echo "✓ Merge requirements validation passed"

  test-workflow-integration:
    name: "Test Workflow Integration"
    runs-on: ubuntu-latest
    needs: [test-pr-triggers, test-status-checks]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Test workflow dependencies
        run: |
          echo "Testing workflow integration..."

          # Verify that workflows have proper triggers
          if grep -q "pull_request" .github/workflows/validate.yml; then
            echo "✓ Validate workflow triggers on PR"
          else
            echo "ERROR: Validate workflow missing PR trigger"
            exit 1
          fi

          if grep -q "branches:" .github/workflows/release.yaml && \
             grep -q "main" .github/workflows/release.yaml; then
            echo "✓ Release workflow triggers on main branch"
          else
            echo "ERROR: Release workflow missing main branch trigger"
            exit 1
          fi

      - name: Test package.json scripts
        run: |
          echo "Testing package.json test configuration..."
          if npm run test:pr-workflow --silent 2>/dev/null; then
            echo "✓ Test script works correctly"
          else
            echo "WARNING: Test script has issues"
          fi

          # Verify lint script exists
          if npm run lint --silent 2>/dev/null; then
            echo "✓ Lint script works"
          else
            echo "WARNING: Lint script may have issues"
          fi

      - name: Verify all tests completed
        run: |
          echo "✓ All PR workflow tests completed successfully"
          echo "PR workflow validation is working correctly"